### ISSUE TITLE
AIO App Init Fails on Latest Version

### ISSUE THREAD

**Issue by klcodanr** [adobe/aio-cli#162]
### Expected Behaviour

AIO App is initialized

### Actual Behaviour

CLI fails with error

#### Steps to Reproduce

- Update AIO CLI to 3.4.1
- run the command `aio app init [appname]`

#### Platform and Version

@adobe/aio-cli/3.4.1 darwin-x64 node-v14.2.0

#### Logs taken while reproducing problem

PRFT-14142-MAC:aio-manager dan.klco$ aio app init my-aio-app
Error: IMS context '$cli' is not configured
    at Object._resolveContext (/usr/local/lib/node_modules/@adobe/aio-cli/node_modules/@adobe/aio-lib-ims/src/token-helper.js:70:29)
    at async InitCommand.run (/usr/local/lib/node_modules/@adobe/aio-cli/node_modules/@adobe/aio-cli-plugin-app/src/commands/app/init.js:42:27)
    at async InitCommand._run (/usr/local/lib/node_modules/@adobe/aio-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/node_modules/@adobe/aio-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (/usr/local/lib/node_modules/@adobe/aio-cli/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/usr/local/lib/node_modules/@adobe/aio-cli/node_modules/@oclif/command/lib/command.js:43:20)

**Comment by shazron** [comment]
@klcodanr until a patch comes in, can you run `aio login` beforehand first before calling `aio app init`
