### ISSUE TITLE
The @oclif/core update to v2.x is failing

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli#462]
See #454 for unit test errors.

```
> @adobe/aio-cli@9.3.0 test /home/runner/work/aio-cli/aio-cli
> jest --ci

FAIL test/commands/update.test.js
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/home/runner/work/aio-cli/aio-cli/node_modules/@oclif/core/package.json'

      11 |  */
      12 |
    > 13 | const { Command, Flags, CliUx: cli } = require('@oclif/core')
         |                                        ^
      14 | const inquirer = require('inquirer')
      15 | const chalk = require('chalk')
      1[6](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:7) | const ora = require('ora')

      at createError (node_modules/memfs/lib/volume.js:131:1[7](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:8))
      at throwError (node_modules/memfs/lib/volume.js:140:11)
      at Volume.Object.<anonymous>.Volume.openFile (node_modules/memfs/lib/volume.js:[8](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:9)13:[9](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:10))
      at Volume.Object.<anonymous>.Volume.openBase (node_modules/memfs/lib/volume.js:817:25)
      at Volume.Object.<anonymous>.Volume.openSync (node_modules/memfs/lib/volume.js:828:21)
      at Volume.Object.<anonymous>.Volume.readFileBase (node_modules/memfs/lib/volume.js:914:23)
      at Volume.Object.<anonymous>.Volume.readFileSync (node_modules/memfs/lib/volume.js:929:21)
      at requireJson (node_modules/@oclif/core/lib/util.js:[10](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:11)5:26)
      at Object.<anonymous> (node_modules/@oclif/core/lib/cli-ux/config.js:9:53)
      at Object.<anonymous> (node_modules/@oclif/core/lib/cli-ux/index.js:9:18)
      at Object.<anonymous> (node_modules/@oclif/core/lib/command.js:7:18)
      at Object.<anonymous> (node_modules/@oclif/core/lib/index.js:5:19)
      at Object.require (src/commands/update.js:13:40)
      at Object.require (test/commands/update.test.js:27:20)

PASS test/helpers.test.js
FAIL test/commands/rollback.test.js
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/home/runner/work/aio-cli/aio-cli/node_modules/@oclif/core/package.json'

      [11](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:12) |  */
      [12](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:13) |
    > [13](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:14) | const { Command, Flags, CliUx: cli } = require('@oclif/core')
         |                                        ^
      [14](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:15) | const inquirer = require('inquirer')
      [15](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:16) | const { prompt, hideNPMWarnings } = require('../helpers')
      [16](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:17) |

      at createError (node_modules/memfs/lib/volume.js:131:[17](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:18))
      at throwError (node_modules/memfs/lib/volume.js:140:11)
      at Volume.Object.<anonymous>.Volume.openFile (node_modules/memfs/lib/volume.js:813:9)
      at Volume.Object.<anonymous>.Volume.openBase (node_modules/memfs/lib/volume.js:817:25)
      at Volume.Object.<anonymous>.Volume.openSync (node_modules/memfs/lib/volume.js:828:21)
      at Volume.Object.<anonymous>.Volume.readFileBase (node_modules/memfs/lib/volume.js:914:23)
      at Volume.Object.<anonymous>.Volume.readFileSync (node_modules/memfs/lib/volume.js:929:21)
      at requireJson (node_modules/@oclif/core/lib/util.js:105:26)
      at Object.<anonymous> (node_modules/@oclif/core/lib/cli-ux/config.js:9:53)
      at Object.<anonymous> (node_modules/@oclif/core/lib/cli-ux/index.js:9:[18](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:19))
      at Object.<anonymous> (node_modules/@oclif/core/lib/command.js:7:18)
      at Object.<anonymous> (node_modules/@oclif/core/lib/index.js:5:[19](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:20))
      at Object.require (src/commands/rollback.js:13:40)
      at Object.require (test/commands/rollback.test.js:27:[20](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:21))

FAIL test/commands/discover.test.js
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/home/runner/work/aio-cli/aio-cli/node_modules/@oclif/core/package.json'

      11 |  */
      12 |
    > 13 | const { Command, Flags, CliUx: cli } = require('@oclif/core')
         |                                        ^
      14 | const fetch = require('node-fetch')
      15 | const inquirer = require('inquirer')
      16 | const { sortValues } = require('../helpers')

      at createError (node_modules/memfs/lib/volume.js:131:17)
      at throwError (node_modules/memfs/lib/volume.js:140:11)
      at Volume.Object.<anonymous>.Volume.openFile (node_modules/memfs/lib/volume.js:813:9)
      at Volume.Object.<anonymous>.Volume.openBase (node_modules/memfs/lib/volume.js:817:25)
      at Volume.Object.<anonymous>.Volume.openSync (node_modules/memfs/lib/volume.js:828:[21](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:22))
      at Volume.Object.<anonymous>.Volume.readFileBase (node_modules/memfs/lib/volume.js:914:[23](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:24))
      at Volume.Object.<anonymous>.Volume.readFileSync (node_modules/memfs/lib/volume.js:929:21)
      at requireJson (node_modules/@oclif/core/lib/util.js:105:26)
      at Object.<anonymous> (node_modules/@oclif/core/lib/cli-ux/config.js:9:53)
      at Object.<anonymous> (node_modules/@oclif/core/lib/cli-ux/index.js:9:18)
      at Object.<anonymous> (node_modules/@oclif/core/lib/command.js:7:18)
      at Object.<anonymous> (node_modules/@oclif/core/lib/index.js:5:19)
      at Object.require (src/commands/discover.js:13:40)
      at Object.require (test/commands/discover.test.js:15:20)

FAIL test/hookerror.test.js
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/home/runner/work/aio-cli/aio-cli/node_modules/@oclif/core/package.json'

      [25](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:26) | jest.mock('@oclif/core', () => {
      [26](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:27) |   return {
    > [27](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:28) |     ...jest.requireActual('@oclif/core'),
         |             ^
      [28](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:29) |     Config: {
      [29](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:30) |       load: () => {
      [30](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:31) |         return {

      at createError (node_modules/memfs/lib/volume.js:1[31](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:32):17)
      at throwError (node_modules/memfs/lib/volume.js:140:11)
      at Volume.Object.<anonymous>.Volume.openFile (node_modules/memfs/lib/volume.js:813:9)
      at Volume.Object.<anonymous>.Volume.openBase (node_modules/memfs/lib/volume.js:817:25)
      at Volume.Object.<anonymous>.Volume.openSync (node_modules/memfs/lib/volume.js:828:21)
      at Volume.Object.<anonymous>.Volume.readFileBase (node_modules/memfs/lib/volume.js:914:23)
      at Volume.Object.<anonymous>.Volume.readFileSync (node_modules/memfs/lib/volume.js:929:21)
      at requireJson (node_modules/@oclif/core/lib/util.js:105:26)
      at Object.<anonymous> (node_modules/@oclif/core/lib/cli-ux/config.js:9:53)
      at Object.<anonymous> (node_modules/@oclif/core/lib/cli-ux/index.js:9:18)
      at Object.<anonymous> (node_modules/@oclif/core/lib/command.js:7:18)
      at Object.<anonymous> (node_modules/@oclif/core/lib/index.js:5:19)
      at requireActual (test/hookerror.test.js:27:13)
      at Object.require (src/index.js:13:[34](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:35))
      at Object.require (test/hookerror.test.js:13:21)

FAIL test/index.test.js
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/home/runner/work/aio-cli/aio-cli/node_modules/@oclif/core/package.json'

      15 | jest.mock('@oclif/core', () => {
      16 |   return {
    > 17 |     ...jest.requireActual('@oclif/core'),
         |             ^
      18 |     Config: {
      19 |       load: () => ({})
      20 |     },

      at createError (node_modules/memfs/lib/volume.js:131:17)
      at throwError (node_modules/memfs/lib/volume.js:1[40](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:41):11)
      at Volume.Object.<anonymous>.Volume.openFile (node_modules/memfs/lib/volume.js:813:9)
      at Volume.Object.<anonymous>.Volume.openBase (node_modules/memfs/lib/volume.js:817:25)
      at Volume.Object.<anonymous>.Volume.openSync (node_modules/memfs/lib/volume.js:828:21)
      at Volume.Object.<anonymous>.Volume.readFileBase (node_modules/memfs/lib/volume.js:914:23)
      at Volume.Object.<anonymous>.Volume.readFileSync (node_modules/memfs/lib/volume.js:929:21)
      at requireJson (node_modules/@oclif/core/lib/util.js:105:26)
      at Object.<anonymous> (node_modules/@oclif/core/lib/cli-ux/config.js:9:53)
      at Object.<anonymous> (node_modules/@oclif/core/lib/cli-ux/index.js:9:18)
      at Object.<anonymous> (node_modules/@oclif/core/lib/command.js:7:18)
      at Object.<anonymous> (node_modules/@oclif/core/lib/index.js:5:19)
      at requireActual (test/index.test.js:17:13)
      at Object.require (src/index.js:13:34)
      at Object.require (test/index.test.js:13:21)

-----------------|---------|----------|---------|---------|-------------------
File             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------|---------|----------|---------|---------|-------------------
All files        |   14.01 |    25.27 |   16.66 |   14.49 |                   
 src             |   71.[42](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:43) |    74.19 |   88.88 |   71.42 |                   
  helpers.js     |     100 |      100 |     100 |     100 |                   
  index.js       |       0 |        0 |       0 |       0 | 13-42             
  types.jsdoc.js |       0 |        0 |       0 |       0 |                   
 src/commands    |       0 |        0 |       0 |       0 |                   
  discover.js    |       0 |        0 |       0 |       0 | 13-1[44](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:45)            
  rollback.js    |       0 |        0 |       0 |       0 | 13-154            
  update.js      |       0 |        0 |       0 |       0 | 13-260            
-----------------|---------|----------|---------|---------|-------------------
Jest: "global" coverage threshold for statements (100%) not met: 14.01%
Jest: "global" coverage threshold for branches (100%) not met: 25.27%
Jest: "global" coverage threshold for lines (100%) not met: 14.[49](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:50)%
Test Suites: 5 failed, 1 passed, 6 total
Tests:       14 passed, 14 total
Snapshots:   0 total
Time:        3.[83](https://github.com/adobe/aio-cli/actions/runs/5471002362/jobs/9961696035?pr=454#step:8:84)1 s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
```

**Comment by shazron** [comment]
Depends on #467

**Comment by shazron** [comment]
Fixed
